app:
  app_name: GatewayService
  debug: false
  host: 0.0.0.0
  port: 8080
  logging:
    logger_name: GatewayServiceLogger
    app_name: GatewayService
    level: info
    file: gateway_service.log
    file_level: info